### 1.5 NumPy

In [1]:
import numpy as np

In [2]:
### 1.5.2 NumPy配列の生成

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

### 1.5.3 NumPyの算術計算

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + ｙ # 要素ごとの足し算

array([3., 6., 9.])

In [6]:
x - y

array([-1., -2., -3.])

In [7]:
x * y # element-wise product

array([ 2.,  8., 18.])

In [8]:
x / y

array([0.5, 0.5, 0.5])

In [9]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

### 1.5.4 NumPyのN次元配列

In [10]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int32')

In [13]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [14]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [15]:
print(A)

[[1 2]
 [3 4]]


In [16]:
A * 10

array([[10, 20],
       [30, 40]])

### 1.5.5 ブロードキャスト

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

### 1.5.6 要素へのアクセス

In [18]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(x)

[1. 2. 3.]


In [19]:
X[0] # 0行目

array([51, 55])

In [20]:
X[0][1] # (0, 1)の要素

55

In [21]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [22]:
X = X.flatten() # Xを1次元の配列へ変換
print(X)

[51 55 14 19  0  4]


In [23]:
X[np.array([0, 2, 4])] # インデックスが0, 2, 4番目の要素を取得

array([51, 14,  0])

In [24]:
X > 15

array([ True,  True, False,  True, False, False])

In [25]:
X[X>15]

array([51, 55, 19])